### ISSUE TITLE
Build PE image for CI

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-reference#124]
Update the build scripts to build an image on aarch64 as well. We also need to create a PE image build that halts after booting such that we can have the same unit and integration tests implemented on both platforms.

Once this is done, we need to update the [S3 manifest](https://github.com/rust-vmm/vmm-reference/blob/master/tests/tools/s3/resource_manifest.json), and upload the images & the scripts to the S3 bucket used for testing.

For this task we need to update the scripts that build resources: https://github.com/rust-vmm/vmm-reference/tree/master/resources

**Comment by lauralt** [comment]
Fixed by #158
