### ISSUE TITLE
Create a minimal FDT

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-reference#126]
Import the rust-vmm/vm-fdt code and define a minimal FDT. At a minimum the FDT should at least have the memory, vcpu, interrupts, and timer nodes.The FDT then needs to be initialized as part of the Vmm crate. We need to find the best place for this initialization.

**Comment by uran0sH** [comment]
Could I do it if no one work on it?

**Comment by andreeaflorescu** [comment]
Yes, you can pick this up, but it might not be the best good first issue. The minimal FDT is already created, but there are some shortcomings to it, namely it's pretty hardcoded and the initialization is happening here: https://github.com/rust-vmm/vmm-reference/blob/ceacce791beed583dcc6cd6df95e72c47ef0f3d4/src/vmm/src/lib.rs#L314. One of the problems is that we need the vcpu count, and we did a pretty ugly hack to get it, as briefly explained here: https://github.com/rust-vmm/vmm-reference/blob/ceacce791beed583dcc6cd6df95e72c47ef0f3d4/src/vmm/src/lib.rs#L184

**Comment by andreeaflorescu** [comment]
And here is the code for setting up the FDT: https://github.com/rust-vmm/vmm-reference/blob/ceacce791beed583dcc6cd6df95e72c47ef0f3d4/src/arch/src/lib.rs#L66

**Comment by andreeaflorescu** [comment]
We can reduce the scope of this issue so that you can work on it. Instead of fixing all the shortcomings of this, we can do the following instead:
- remove the hard coded addresses for the RTC and the Serial Console device, and pass them as a parameter instead (https://github.com/rust-vmm/vmm-reference/blob/ceacce791beed583dcc6cd6df95e72c47ef0f3d4/src/arch/src/lib.rs#L177 and https://github.com/rust-vmm/vmm-reference/blob/ceacce791beed583dcc6cd6df95e72c47ef0f3d4/src/arch/src/lib.rs#L247)
- as this will add quite a few parameters to the `create_fdt` function, we can re-implement it using the Builder Pattern: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html

The second bullet point can be done afterwards.

**Comment by uran0sH** [comment]
Ok, I also have send message to you in Slack.
