### ISSUE TITLE
Import system allocator (once it becomes available)

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-reference#132]
Adapt the code in vmm-reference to use a system allocator for interrupts and MMIO ranges instead of having them statically assigned.

**Comment by ramyak-mehra** [comment]
I would like to take this up.
a general overview of this particular PR according to me would include:
* Import and adding the vm-allocator crate
* Refactor code where we manually allocate memory. something similar to [this](https://github.com/rust-vmm/vmm-reference/blob/ad371898afe7d1d230ab4f8a5148d1aa511eed69/src/vmm/src/lib.rs#L351) and [this](https://github.com/rust-vmm/vmm-reference/blob/ad371898afe7d1d230ab4f8a5148d1aa511eed69/src/vmm/src/lib.rs#L342)

Am I missing something please do mention
