### ISSUE TITLE
Generate test resources as per manifest

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-reference#163]
Right now the test resources are generated in various places under `/tmp` or a folder that the user specified. This is making it a bit hard to upload new resources to S3. To make this easier, we should just have all images that need to be uploaded in the same folder, following the paths as specified by the resources manifest JSON file. With this, we could just upload the whole folder to S3.

**Comment by lauralt** [comment]
Fixed by #165
