### ISSUE TITLE
consume i8042 device from vm-superio

### ISSUE THREAD

**Issue by lauralt** [rust-vmm/vmm-reference#198]
At this point we don't have an implementation of the i8042 device in vmm-reference, and we don't do anything for [the related vcpu exits](https://github.com/rust-vmm/vmm-reference/blob/ceacce791beed583dcc6cd6df95e72c47ef0f3d4/src/vm-vcpu/src/vcpu/mod.rs#L685). We should consume the device from [vm-superio](https://github.com/rust-vmm/vm-superio/blob/main/crates/vm-superio/src/i8042.rs) in order to gracefully handle the shutdown.

**Comment by andreeaflorescu** [comment]
Task breakdown:
- Define an i8042Wrapper in devices/src/legacy that extends the upstream i8042. This should be defined similar to the RtcWrapper or the SerialWrapper.
- Implement the `MutDevicePio` trait for the i8042 Wrapper. A good example of how this can be done is here: https://github.com/google/crosvm/blob/cbddc592dd256155f14054e10b5c539c3c6c794a/devices/src/i8042.rs#L23
- in vmm/src/lib.rs initialize the i8042 wrapper and add it to the `device_mgr` (this should also include calling register_irqfd)

Once these things are done, we can test the integration works by removing "reboot=t" from the command line defined in `vmm/src/lib.rs` and check that we still properly run the tests that expect the vmm to exit.

**Comment by lauralt** [comment]
Fixed by #215
