### ISSUE TITLE
Linux image for testing aarch64

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-reference#218]
We need to check if the existing image we're using for testing aarch64 has all required features enabled. The goal is to run the same integration tests on both x86_64 and aarch64. Where there might be problems: virtio block & virtio net.

Once the required functionality is added on aarch64, we should enable the integration tests for aarch64 as well. If the existing image does not have the required support, we'll need to create a new image, and publish it to the S3 resources bucket.

**Comment by ramyak-mehra** [comment]
#225 Closes this.
We decided on create the config for linux 5.4 from config file from firecrackers's 5.10 config file because of some configuration changes that were done. With the help of the newly generated linux 5.4 config file all the resources are generated
