### ISSUE TITLE
Return error when vcpu number is invalid

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-reference#22]
We should validate the vcpu number when parsing the command line argument, and return an error in case it is invalid (it should be between 1 and 256).

Right now the VMM process just freezes when you pass ```--vcpus num_vcpus=0```. We should also add a regression test to check that passing ```--vcpus num_vcpus=0``` returns an error and then the process is terminated.

**Comment by dodsonmg** [comment]
Is this addressed by ec7a6647e2b069c18e30644982d16f5eca410edf, or is it a different issue?

**Comment by andreeaflorescu** [comment]
@dodsonmg looks like this is indeed addressed. Closing the issue.
