### ISSUE TITLE
vm-superio Serial not working

### ISSUE THREAD

**Issue by chintansheth1711** [rust-vmm/vmm-reference#234]
In new commit, following error arises
error[E0432]: unresolved import `serial::Serial`
.cargo/registry/src/github.com-1ecc6299db9ec823/vm-superio-0.5.0/src/lib.rs:26:9
pub use serial::Serial;

**Comment by andreeaflorescu** [comment]
Where are you getting this error? Can you please write some reproduction steps with what you are doing?

**Comment by chintansheth1711** [comment]
resolved
