### ISSUE TITLE
Test VMM with 1 and 2 guest memory regions

### ISSUE THREAD

**Issue by aghecenco** [rust-vmm/vmm-reference#25]
The reference VMM tests should cover use cases where the guest memory fits before the MMIO space, as well as cases where it has to be split in 2 regions surrounding it.
The test also has to verify that `build_bootparams` adds one E820 entry for guest memory (start address of the MMIO gap <= last address of guest memory <= end address of the MMIO gap) and respectively two E820 entries for guest memory (last address of guest memory > end address of the MMIO gap).

**Comment by aghecenco** [comment]
Partially covered by https://github.com/rust-vmm/vmm-reference/pull/40/commits/840c8910fa830d2347e9a2f778a3d2c179db8066 + https://github.com/rust-vmm/vmm-reference/pull/40/commits/44c20a68cc69c5cb2bee8d0fdccaee6c3b03da9c
(these exercise the configuration path)
What remains is to write full-fledged VMM tests that spawn the full VMM.

**Comment by andreeaflorescu** [comment]
Fixed by: #53
