### ISSUE TITLE
Integration test that verifies the available CPUs from inside the guest

### ISSUE THREAD

**Issue by aghecenco** [rust-vmm/vmm-reference#27]
Add an integration test that boots a guest and verifies that the CPUs by the VMM are indeed available (parsing `/proc/cpuinfo` is a good start).

**Comment by dodsonmg** [comment]
Is this still open?  If so, I'd like to have a go, but might need some help.

- Are you looking for a test to land in `vmm-reference/src/vmm/tests/integration_tests.rs`?
- Are there any similar tests anywhere in `rust-vmm` that parse and pull information from inside the vm for use externally in a test?

**Comment by andreeaflorescu** [comment]
> Is this still open? If so, I'd like to have a go, but might need some help.
> 

Yap, we can help out here.

> * Are you looking for a test to land in `vmm-reference/src/vmm/tests/integration_tests.rs`?

We were looking for a Python integration test. These are placed under [vmm-reference/tests/](https://github.com/rust-vmm/vmm-reference/tree/master/tests). I think it should be possible to do it in Rust as well, but there are a few examples of how to communicate with the VM in Python already if you'd like to reuse those.

> * Are there any similar tests anywhere in `rust-vmm` that parse and pull information from inside the vm for use externally in a test?

The 2 things that we need to do to be able to check the number of cpus are:
- send a command to the VM; an example of this is in the the test that [shuts down the VM](https://github.com/rust-vmm/vmm-reference/blob/1c5ed93058ba83b87a18052a8ef2975752932edd/tests/test_run_reference_vmm.py#L91)
- check the response of the command; we do not have an example here, but I think that as a first iteration we can work with something similar to the [`expect_string`](https://github.com/rust-vmm/vmm-reference/blob/1c5ed93058ba83b87a18052a8ef2975752932edd/tests/test_run_reference_vmm.py#L99) function to read the stdout of the process.

**Comment by dodsonmg** [comment]
Closed by #53?
