### ISSUE TITLE
make_busybox.sh doesn't work

### ISSUE THREAD

**Issue by qhjindev** [rust-vmm/vmm-reference#44]
When I started building the kernel according the getting-started.md, I executed the cmd under ubuntu to build an elf image:
  ./make_busybox.sh
But I can't see anything created and no output from the command line.

**Comment by andreeaflorescu** [comment]
We need to update the docs. The scripts for creating a busybox were updated. You should use `make_kernel_image.sh` instead.

There are a few usage examples here: https://github.com/rust-vmm/vmm-reference/blob/master/.buildkite/deps-pipeline.yml#L3

Let us know if you need additional help.
