### ISSUE TITLE
Implement a more generic parser for command line arguments

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-reference#55]
We currently duplicate the parsing logic in the `try_from` functions of `MemoryConfig`, `VcpuConfig`, `KernelConfig`, `NetConfig`, `BlockConfig`. As we add more devices and configuration, this duplication generates too much boilerplate code.

We should try to see if we can somehow reduce this duplication (without adding new rust crates dependencies).

**Comment by FedericoPonzi** [comment]
Could you please assign this to me?

**Comment by gabhijit** [comment]
Related: I am thinking whether it's a good idea to use `builder` pattern here. Something along the lines of [`hyper Request`](https://docs.rs/http/0.1.10/http/request/struct.Builder.html) builder? 

So the code would look like - 
```rust 
let vmm_cfg = VMMConfig::builder()
.memory(...)
.kernel(...)
.net(...)
``` 
And with right set of defaults, so not everything becomes a required config?

**Comment by andreeaflorescu** [comment]
> Related: I am thinking whether it's a good idea to use `builder` pattern here. Something along the lines of [`hyper Request`](https://docs.rs/http/0.1.10/http/request/struct.Builder.html) builder?
> 
> So the code would look like -
> 
> ```rust
> let vmm_cfg = VMMConfig::builder()
> .memory(...)
> .kernel(...)
> .net(...)
> ```
> 

I personally like the builder pattern, I wonder how much it helps in this scenario. A prototype would be nice.

> And with right set of defaults, so not everything becomes a required config?

Besides the kernel path, for everything else we can have defaults.

@gabhijit are you interested in contributing your proposal?

**Comment by gabhijit** [comment]
@andreeaflorescu , Sure I can give it a try . Let me create a separate issue?

**Comment by andreeaflorescu** [comment]
> @andreeaflorescu , Sure I can give it a try . Let me create a separate issue?

Yap, sounds good.
