### ISSUE TITLE
Small Improvements to integration tests

### ISSUE THREAD

**Issue by gabhijit** [rust-vmm/vmm-reference#63]
Suggesting a couple of improvements to integration tests inside `tests/test_run_reference_vmm.py` 

1. This one is more like a 'nit'  

```python 
def start_vmm_process(kernel_path, disk_path, num_vcpus = 1, mem_size_mib = 1024):
   ...
```
In the function above, `disk_path` parameter should be optional, then it will also be consistent with other semantics where only kernel path is a required parameter while configuring the VM. 

2. This one is more like a bug - 

```python 

def expect_string(vmm_process, expected_string):
    while True:
        nextline = vmm_process.stdout.readline()
        if expected_string in nextline.decode():
 ...

```

The `while True` loop above does not break and  if the case is failing, it just remains stuck (Observed it a couple of times while running tests that failed). The only option is to `kill` the Python process. This needs to be handled with `subprocess.wait` - Which throws `TimeoutExpired` and catch it around some number of retries and fail the test. It is safe to catch the exception and retry [as discussed here](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait)

**Comment by andreeaflorescu** [comment]
> 1. This one is more like a bug -
> 
> ```python
> def expect_string(vmm_process, expected_string):
>     while True:
>         nextline = vmm_process.stdout.readline()
>         if expected_string in nextline.decode():
>  ...
> ```
> 
> The `while True` loop above does not break and if the case is failing, it just remains stuck (Observed it a couple of times while running tests that failed). The only option is to `kill` the Python process. This needs to be handled with `subprocess.wait` - Which throws `TimeoutExpired` and catch it around some number of retries and fail the test. It is safe to catch the exception and retry [as discussed here](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait)

This one is already reported: https://github.com/rust-vmm/vmm-reference/issues/18
We were thinking of fixing it by using pytest-timeout, but we did not install it in the container yet. I'll publish a new container version, and then install `pytest-timeout` as well, but we can also fix it as you suggested. Are you interested in submitting a PR with your suggestion?

**Comment by lauralt** [comment]
@gabhijit I updated the issue description with the explicit code, linking a file line was not a good idea.

**Comment by gabhijit** [comment]
> @gabhijit I updated the issue description with the explicit code, linking a file line was not a good idea.

Thanks. May be that link got accidentally left out. From what I remember, I tried to use inline preview from github itself, but it somehow didn't work.

**Comment by gabhijit** [comment]
> > 1. This one is more like a bug -
> > 
> > ```python
> > def expect_string(vmm_process, expected_string):
> >     while True:
> >         nextline = vmm_process.stdout.readline()
> >         if expected_string in nextline.decode():
> >  ...
> > ```
> > 
> > 
> > The `while True` loop above does not break and if the case is failing, it just remains stuck (Observed it a couple of times while running tests that failed). The only option is to `kill` the Python process. This needs to be handled with `subprocess.wait` - Which throws `TimeoutExpired` and catch it around some number of retries and fail the test. It is safe to catch the exception and retry [as discussed here](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait)
> 
> This one is already reported: #18
> We were thinking of fixing it by using pytest-timeout, but we did not install it in the container yet. I'll publish a new container version, and then install `pytest-timeout` as well, but we can also fix it as you suggested. Are you interested in submitting a PR with your suggestion?

I generally look around before submitting the issues. Somehow it's hard to find similar issues on github! :-(  Also, I am not entirely sure `pytest-timeout` will explicitly tell the failure, where as raising exception would tell the actual test case that failed.  

I will submit a PR about this sometime next week.

**Comment by lauralt** [comment]
> > @gabhijit I updated the issue description with the explicit code, linking a file line was not a good idea.
> 
> Thanks. May be that link got accidentally left out. From what I remember, I tried to use inline preview from github itself, but it somehow didn't work.

If the file changes in the meantime, the link will point to the same line number, not the same code line. I always forget about this :).

**Comment by gabhijit** [comment]
#63 Fixes this. Closing.
