### ISSUE TITLE
Update kvm-ioctls version to the latest one

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vmm-reference#74]
We're using an outdated version of kvm-ioctls. In the latest version there are also some API changes that we need to adapt to.

To update the version of kvm-ioctls, we need to update the following `Cargo.toml` files:
- src/devices/Cargo.toml
- src/vm-vcpu/Cargo.toml
- src/vmm/Cargo.toml

As part of this PR, the Cargo.lock file also needs to be updated.

**Comment by anth1y** [comment]
I'd like to take this on if no one else has...

**Comment by lauralt** [comment]
Hi, @anth1y! The issue was already fixed in https://github.com/rust-vmm/vmm-reference/pull/85. We forgot to close it :(.
If you're interested in contributing to `vmm-reference`, [this one](https://github.com/rust-vmm/vmm-reference/issues/98) would be another good first issue.
